### ISSUE TITLE
64 bit 

### ISSUE THREAD

**Issue by rolexwatch123** [nepcat/cathook#1]
Will this ever be updated to 64 bit or are there other cheats for Linux that work on 64 bit?

**Comment by nepcat** [comment]
There will be no 64 bit version of cathook from nullworks as BenCat07 said. I'm not going to work on it either, it's just a reupload of cathook from nullworks.

**Comment by rolexwatch123** [comment]
Are there any other cheats for Linux?

**Comment by nepcat** [comment]
There are none, at least not publicly available.

**Comment by rolexwatch123** [comment]
Are there any windows ones?

**Comment by nepcat** [comment]
> Are there any windows ones?

https://github.com/emilyinure/haven-tf2
